# Core
PROJECT_NAME={{PROJECT_NAME}}
APP_VERSION=latest

# App paths in repository root
FRONTEND_APP_DIR={{FRONTEND_APP_DIR}}
BACKEND_APP_DIR={{BACKEND_APP_DIR}}

# Ports
FRONTEND_PORT={{FRONTEND_PORT}}
BACKEND_PORT={{BACKEND_PORT}}
DB_PORT={{DB_PORT}}

# Database
POSTGRES_DB={{POSTGRES_DB}}
POSTGRES_USER={{POSTGRES_USER}}
POSTGRES_PASSWORD={{POSTGRES_PASSWORD}}

# Runtime commands
FRONTEND_DEV_CMD={{FRONTEND_DEV_CMD}}
BACKEND_DEV_CMD={{BACKEND_DEV_CMD}}
FRONTEND_PROD_CMD={{FRONTEND_PROD_CMD}}
BACKEND_PROD_CMD={{BACKEND_PROD_CMD}}

# Optional migration command, for example:
# BACKEND_MIGRATION_CMD=npx prisma migrate deploy
BACKEND_MIGRATION_CMD={{BACKEND_MIGRATION_CMD}}

